"use strict";
exports.__esModule = true;
var Person_1 = require("./Person");
var SlotsLuckyBoy_1 = require("./SlotsLuckyBoy");
var rls = require('readline-sync');
var yourself = new Person_1.Person("Ignacio", "González", 11111111, "04-08-2004", 100);
var chosenTopic = rls.question("Choose a number to select the game topic:" + "\n" + "[1] Lucky Boy" + "\n" + "[2] Lucky Man" + "\n" + "Your selection is: ");
var slotsLuckyBoy = new SlotsLuckyBoy_1.SlotsLuckyBoy(chosenTopic, 1000);
console.log(slotsLuckyBoy.getTopic());
console.log(slotsLuckyBoy.getBet());
